default:
  image: chantalkeller/javatest:latest

compiling:
  stage: build
  script:
    - export LANG=C.UTF-8
    - cd code
    - mkdir -p bin
    - javac -d bin src/*/*.java

tests-weakMeals:
  stage: test
  script:
    - export LANG=C.UTF-8
    - cd code
    - mkdir -p bin
    - javac -d bin src/*/*.java
    - javac -d bin -cp bin:/usr/share/java/junit-platform-console-standalone-1.9.1.jar test/WeekMealsTest.java
    - java -jar /usr/share/java/junit-platform-console-standalone-1.9.1.jar -cp bin --select-class WeekMealsTest

tests-ControllerButtons:
  stage: test
  script:
    - export LANG=C.UTF-8
    - cd code
    - mkdir -p bin
    - javac -d bin src/*/*.java
    - javac -d bin -cp bin:/usr/share/java/junit-platform-console-standalone-1.9.1.jar test/ControllerButtonsTest.java
    - java -jar /usr/share/java/junit-platform-console-standalone-1.9.1.jar -cp bin --select-class ControllerButtonsTest

